---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: upbound-system
stringData:
  creds: |
    $base64encoded_aws_creds
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: $providerconfig_aws_name
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: aws-secret
      key: creds
