apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Registry
metadata:
  name: perftestregistry$random_suffix
spec:
  providerConfigRef:
    name: provider-azure
  forProvider:
    adminEnabled: false
    location: "West Europe"
    resourceGroupNameSelector:
      matchLabels:
        purpose: perf-test
    sku: Standard
