apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: piotr-azure-perf-test
  region: eu-central-1
  version: "1.25"

nodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 1
