apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-$cluster_name
  region: $eks_region
  version: "1.25"

nodeGroups:
  - name: ng-1
    instanceType: $eks_node
    desiredCapacity: 1
