---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: gcp-config
spec:
  args: []
    # - '-d'
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  package: $gcp_provider_image$gcp_provider_version
  controllerConfigRef:
    name: gcp-config
