---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-creds
  namespace: upbound-system
type: Opaque
data:
  creds: $base64encoded_gcp_creds
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: $providerconfig_gcp_name
spec:
  projectID: $gcp_project_id
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: gcp-creds
      key: creds
