apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-release-candidates-provider-azure-registry
spec:
  package: xpkg.upbound.io/upbound-release-candidates/provider-azure-containerregistry:v0.1.0-rc.0
