apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: perftestpiotrcostam
spec:
  forProvider:
    location: EU
    storageClass: STANDARD
    project: squad-platform-playground
    labels:
      owner: squad-platform
      purpose: performance-testing
  providerConfigRef:
      name: default
