apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Registry
metadata:
  name: perftestregistry$random_suffix
spec:
  providerConfigRef:
    name: default
  forProvider:
    adminEnabled: false
    location: "West Europe"
    resourceGroupNameSelector:
      matchLabels:
        purpose: perf-test
    sku: Standard
# ---
# apiVersion: azure.upbound.io/v1beta1
# kind: ResourceGroup
# metadata:
  # labels:
    # purpose: perf-test
  # name: perf-test-piotr$random_suffix
# spec:
  # forProvider:
    # location: "West Europe"
  # providerConfigRef:
    # name: provider-azure
