apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: upbound-sample-repository
spec:
  forProvider:
    imageTagMutability: IMMUTABLE
    region: eu-central-1
    tags:
      key1: value1
